import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import reactPlugin from "eslint-plugin-react";
import tseslint from "typescript-eslint";
import importPlugin from "eslint-import-plugin";
import { defineConfig, globalIgnores } from "eslint/config";
import eslintConfigPrettier from "eslint-config-prettier/flat";

export default defineConfig([
  globalIgnores(["dist"]),
  {
    files: ["**/*.{ts,tsx}"],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
      eslintConfigPrettier,
    ],
    plugins: {
      import: importPlugin,
      react: reactPlugin,
    },
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    settings: {
      react: { version: "detect" },
    },
    rules: {
      //-- Needed for React Refresh to work properly — ensures that only components are exported from files.
      //-- Ex. src/components/ui/button.tsx
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      //-- No anonymous default exports — forces a name on every component.
      "import/no-anonymous-default-export": "error",
      //-- Disallow exporting function declarations directly (e.g. `export default function Foo() {}`)
      //-- Components must be function declarations, not arrows.
      "react/function-component-definition": [
        "error",
        {
          namedComponents: "function-declaration",
          unnamedComponents: "arrow-function",
        },
      ],
    },
  },
  {
    // shadcn-ui primitives are generated by the shadcn CLI and use forwardRef
    // patterns that don't match `function-declaration`. CLAUDE.md prohibits
    // editing them directly, so exempt the rule here.
    files: ["src/components/ui/**"],
    rules: {
      "react/function-component-definition": "off",
      //-- shadcn primitives export a cva variants object (e.g. buttonVariants) beside
      //-- the component. allowConstantExport only whitelists literals, not cva() calls,
      //-- so the rule still fires here. Off for generated ui/ (do not edit those files).
      "react-refresh/only-export-components": "off",
    },
  },
]);
